---

- name: "Create a virtual machine"

  hosts: all

  become: true

  become_user: root

  remote_user: vagrant

  vars_files:
    - env_vars/main.yml

  roles:

    - base

    - web

    - nginx

    - db 
