---

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Create the Nginx configuration file
  template:
    src: "{{ application_name }}.j2"
    dest: /etc/nginx/sites-available/{{ application_name }}
    backup: yes

- name: Ensure that the default site is disabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    
- name: Ensure that the application site is enabled
  file:
    src: /etc/nginx/sites-available/{{ application_name }}
    dest: /etc/nginx/sites-enabled/{{ application_name }}
    state: link

- name: Ensure Nginx service is started
  service:
    name: nginx
    state: started
    enabled: yes
