---

- name: Install PostgreSQL
  apt:
    pkg:
      - postgresql
      - postgresql-contrib
      - "{{ base_python_package }}-psycopg2"
    state: present
    update_cache: yes

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    state: present

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present
    expires: infinity
    role_attr_flags: CREATEDB,NOSUPERUSER


