---

virtualenv_python_version: "{{ base_python_package }}"

virtualenv_path: "/webapps/opt/venv"

requirements_file: "/webapps/{{ application_name }}/requirements.txt"

gunicorn_user: "{{ application_name }}"

gunicorn_group: webapps

nginx_static_dir: "{{ virtualenv_path }}/static/"

nginx_media_dir: "{{ virtualenv_path }}/media/"


django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  BROKER_URL: "{{ broker_url }}"


